c_args += [
    '-mcpu=cortex-m7',
    '-mfpu=fpv5-d16',
    '-mfloat-abi=hard',
    '--target=arm-none-eabi',
]

linkerscript = '-T' + meson.current_source_dir() + '/STM32H723xG_flash.ld'

c_link_args += [
    '-mcpu=cortex-m7',
    '-mfpu=fpv5-d16',
    '-mfloat-abi=hard',
    '--target=arm-none-eabi',
    linkerscript,
    '-Wl,--gc-sections',
    '-Wl,--print-memory-usage',
]

src += files('Src/interface_implementation.c')

src += files('Src/usb_descriptors.c')

src += files(
    'Src/startup_stm32h723xx.c',
    'Src/stm32h7xx_hal_timebase_tim.c',
    'Src/stm32h7xx_it.c',
    'Src/syscalls.c',
    'Src/sysmem.c',
    'Src/system_stm32h7xx.c',
)

src += files(
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_adc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_adc_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_cec.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_comp.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_cordic.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_cortex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_crc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_crc_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_cryp.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_cryp_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_dac.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_dac_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_dcmi.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_dfsdm.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_dfsdm_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_dma.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_dma2d.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_dma_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_dsi.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_dts.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_eth.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_eth_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_exti.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_fdcan.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_flash.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_flash_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_fmac.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_gfxmmu.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_gpio.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_hash.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_hash_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_hcd.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_hrtim.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_hsem.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_i2c.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_i2c_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_i2s.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_i2s_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_irda.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_iwdg.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_jpeg.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_lptim.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_ltdc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_ltdc_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_mdios.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_mdma.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_mmc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_mmc_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_nand.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_nor.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_opamp.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_opamp_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_ospi.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_otfdec.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_pcd.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_pcd_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_pssi.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_pwr.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_pwr_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_qspi.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_ramecc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_rcc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_rcc_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_rng.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_rng_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_rtc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_rtc_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_sai.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_sai_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_sd.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_sd_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_sdio.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_sdram.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_smartcard.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_smartcard_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_smbus.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_smbus_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_spdifrx.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_spi.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_spi_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_sram.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_swpmi.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_tim.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_tim_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_uart.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_uart_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_usart.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_usart_ex.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_hal_wwdg.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_adc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_bdma.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_comp.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_cordic.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_crc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_crs.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_dac.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_delayblock.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_dma.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_dma2d.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_exti.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_fmac.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_fmc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_gpio.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_hrtim.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_i2c.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_lptim.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_lpuart.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_mdma.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_opamp.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_pwr.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_rcc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_rng.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_rtc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_sdmmc.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_spi.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_swpmi.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_tim.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_usart.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_usb.c',
    'Drivers\STM32H7xx_HAL_Driver\Src\stm32h7xx_ll_utils.c',
)

st_inc = include_directories(
    'Src',
    'Drivers/CMSIS/Device/ST/STM32H7xx/Include',
    'Drivers/STM32H7xx_HAL_Driver/Inc',
)

inc += [st_inc]

add_project_arguments(
    '-DUSE_FULL_LL_DRIVER',
    '-DHSE_VALUE=25000000',
    '-DHSE_STARTUP_TIMEOUT=100',
    '-DLSE_STARTUP_TIMEOUT=5000',
    '-DLSE_VALUE=32768',
    '-DEXTERNAL_CLOCK_VALUE=12288000',
    '-DHSI_VALUE=64000000',
    '-DLSI_VALUE=32000',
    '-DVDD_VALUE=3300',
    '-DUSE_PWR_LDO_SUPPLY',
    '-DSTM32H723xx',
    '-DUSE_HAL_DRIVER',
    language: 'c',
)